
-- Generated by ORDS REST Data Services 24.3.2.r3121009
-- Schema: APPSAMPLS  Date: Tue Feb 11 02:37:04 2025 
--
        
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'priv_test',
      p_base_path      => '/privtest/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'priv_test',
      p_pattern        => 'client/regions',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'priv_test',
      p_pattern        => 'client/regions',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>  
'begin 
  OWA_UTIL.PRINT_CGI_ENV;
End;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'priv_test',
      p_pattern        => 'event/speakers',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'priv_test',
      p_pattern        => 'event/speakers',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         =>  
'begin 
  OWA_UTIL.PRINT_CGI_ENV;
End;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'priv_test',
      p_pattern        => 'client_regions',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'priv_test',
      p_pattern        => 'client_regions',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin 
  OWA_UTIL.PRINT_CGI_ENV;
End;');

    
  ORDS.CREATE_ROLE(p_role_name => 'Client Services Role');
    
  l_roles(1) := 'Client Services Role';
  l_modules(1) := 'priv_test';
  l_patterns(1) := 'priv_test/client/*';
  l_patterns(1) := 'priv_test/client_regions';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'aicd.client.privilege',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'client Reference Data',
      p_description    => 'Provides the ability to read, client reference data',
      p_comments       => NULL);

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
        
COMMIT;

END;
