
-- Generated by ORDS REST Data Services 24.3.2.r3121009
-- Schema: ORDSDEMO  Date: Tue Feb 11 03:20:15 2025 
--
        
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ORDSDEMO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'ordsdemo',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'priv_test',
      p_base_path      => '/priv_test/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'priv_test',
      p_pattern        => 'oci_regions',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'priv_test',
      p_pattern        => 'oci_regions',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin 
  OWA_UTIL.PRINT_CGI_ENV;
End;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'priv_test',
      p_pattern        => 'oci/regions',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'priv_test',
      p_pattern        => 'oci/regions',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin 
  OWA_UTIL.PRINT_CGI_ENV;
End;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'priv_test',
      p_pattern        => 'aicd/speakers',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'priv_test',
      p_pattern        => 'aicd/speakers',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin 
  OWA_UTIL.PRINT_CGI_ENV;
End;');

    
        
COMMIT;

END;